# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f3e204badc2fed32bb107e10012a1fc43d5bf7b8bcef7be03f66c054056065e4547d179943f0fb5727b6b74d2c370d73178e227cbc684a48ae2ccfb34318b50

test:
  secret_key_base: f70284dd237eba71e66e9ae4defbe14c6e8f37b0f492aba41cec15c3e264c2b73c45130a41af11a23896ce164315a67b3dd96360f74c7003b82a69431054b0dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
